
Use o banco de dados: escola_v2.db

COUNT Mostre quantos alunos estão cadastrados na tabela Aluno. (Use a função COUNT)











MIN Mostre a menor mensalidade entre todos os cursos cadastrados. (Use a função MIN)

MAX Mostre a maior nota1 registrada entre todos os alunos. (Use a função MAX)

SUM Calcule o valor total das mensalidades de todos os cursos. (Use a função SUM)

AVG Mostre a média geral da nota2 dos alunos. (Use a função AVG)




