






Faça a query para pegar toda a tabela alunos e imprima na tela.
Obtenha a media entre nota1 e nota2 dos alunos, ordene em ordem decrescente e retorne apenas os 10 maiores notas. No fim imprima na tela a lista desses alunos e suas médias.
Use Left Join com as tabelas Aluno e Turma e imprima todos os dados da tabela.
Usando a query da questão 4, adicione um filtro para pegar apenas os alunos da turma 2 e imprima na tela.

